### ISSUE TITLE
Flick App Week 2 Final Commit

### ISSUE THREAD

**Issue by mceraso** [mceraso/flick-path#3]
Hi CodePath! Please review my app. Excited to learn more this coming week. /cc @codepathreview

**Comment by codepathreview** [comment]
:+1: Nice work! The point of this homework was to get familiar with two common forms of navigation in iOS (push and tab bar). It also provided a chance to extend your Flicks app in new ways.

### Some small comments:
- I cannot build your app :confused: 
  <img width="1018" alt="screen shot 2016-02-09 at 12 09 37 am" src="https://cloud.githubusercontent.com/assets/7917093/12893046/91388d90-cec1-11e5-980a-5d3421d86c7f.png">
- Good job displaying full long overview in Details page :star: 

Excellent submission overall :tada: 

We have a detailed [Project 2 Feedback Guide](http://courses.codepath.com/snippets/ios_university/feedback_guides/project_2_feedback.md) which covers the best practices for implementing this assignment. Read through the feedback guide point-by-point to determine ways you might be able to improve your submission. You should consider going back and implementing these improvements as well. Keep in mind that one of the most important parts of iOS development is learning the correct patterns and conventions.

If you have any particular questions about the assignment or the feedback, feel free to reply here or email us at universitysupport@codepath.com.

**Comment by mceraso** [comment]
Hi codepathreview,

Thank you for the feedback!

D:
Just repushed the code to GitHub. Is it working now? I''ve been running my code on a 5S simulator and with a 5C. Would that help?

/cc @codepathreview
